/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     String[5] name;
    */
    
    @Override
    public void finalize(){
        System.out.println("Finalize called");
        try {
            Agro_Shop_Management.getCon().close();
            //Agro_Shop_Management.getPs().close();
            //Agro_Shop_Management.getSt().close();
            Agro_Shop_Management.setPs(null);
        } catch (SQLException ex) {
           // Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       
    }
    int qun = 0;
    int count = 0;
    float total = 0;
    boolean bt = true;
    
    //Purchase details array to store how many product selected by customer
    ArrayList<PurchaseDetail> purchaseDetails = new ArrayList<>();
    
   void setValue(){    
        //for set value if we not set this values then it give exception 
        this.count = 0;
        this.total = 0;
        CustomerName.setText("");
        CustomerMobile.setText("");
        NoOfProduct.setText("");
        TotalAmountText.setText("");
   
   } 
   
    
    public HomePage() {
        
        this.setResizable(true);
        //this.setVisible(true);
        initComponents();
        seticon();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        this.setSize(x,y);
        addItemToBox();
    }
    
    void addItemToBox(){ // this method fatch the item from the database and set it to jcomboBox(ProductName)
    try {
            
        try (ResultSet rs =  Agro_Shop_Management.getSt().executeQuery("select productName from stock")) {
            while(rs.next()){
                ProductName.addItem(rs.getString(1));
            }
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Exception plz contact the developer ex= "+ex);
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustomerMobile = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TotalAmountText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        AddProduct = new javax.swing.JButton();
        NoOfProduct = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ProductName = new javax.swing.JComboBox<>();
        SaveDetails = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ViewStock = new javax.swing.JButton();
        CustomerDetails = new javax.swing.JButton();
        SearchCustomer = new javax.swing.JButton();
        UpdateStock = new javax.swing.JButton();
        Edit_delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(101, 144, 249));
        setBounds(new java.awt.Rectangle(0, 0, 1080, 720));
        setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(153, 41, 156))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Customer Name");

        CustomerName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CustomerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Customer Mobile");

        CustomerMobile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CustomerMobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CustomerMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMobileActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Purchase Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product Name");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(80, 30, 190, 30);

        TotalAmountText.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TotalAmountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(TotalAmountText);
        TotalAmountText.setBounds(520, 150, 90, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(380, 150, 0, 2);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Quantity");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(370, 40, 101, 14);

        Quantity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(Quantity);
        Quantity.setBounds(380, 80, 103, 30);

        AddProduct.setBackground(new java.awt.Color(255, 153, 153));
        AddProduct.setForeground(new java.awt.Color(255, 102, 102));
        AddProduct.setText("Add");
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });
        jPanel3.add(AddProduct);
        AddProduct.setBounds(120, 160, 100, 23);

        NoOfProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NoOfProduct.setForeground(new java.awt.Color(204, 0, 0));
        NoOfProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(NoOfProduct);
        NoOfProduct.setBounds(520, 190, 80, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Amount ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(390, 150, 90, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("No of Product");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(380, 190, 101, 14);

        ProductName.setBackground(new java.awt.Color(153, 153, 255));
        ProductName.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        ProductName.setForeground(new java.awt.Color(204, 51, 0));
        ProductName.setMaximumRowCount(40);
        jPanel3.add(ProductName);
        ProductName.setBounds(90, 80, 160, 30);

        SaveDetails.setBackground(new java.awt.Color(255, 102, 102));
        SaveDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SaveDetails.setText("Save/ generate bill");
        SaveDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(SaveDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(SaveDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 3), "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 204, 204));

        ViewStock.setBackground(new java.awt.Color(153, 153, 255));
        ViewStock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ViewStock.setForeground(new java.awt.Color(153, 0, 0));
        ViewStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/search.png"))); // NOI18N
        ViewStock.setText("View Stock");
        ViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStockActionPerformed(evt);
            }
        });

        CustomerDetails.setBackground(new java.awt.Color(153, 153, 255));
        CustomerDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CustomerDetails.setForeground(new java.awt.Color(51, 0, 102));
        CustomerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/update.png"))); // NOI18N
        CustomerDetails.setText("Sell Details");
        CustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDetailsActionPerformed(evt);
            }
        });

        SearchCustomer.setBackground(new java.awt.Color(153, 153, 255));
        SearchCustomer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SearchCustomer.setForeground(new java.awt.Color(153, 0, 0));
        SearchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/search.png"))); // NOI18N
        SearchCustomer.setText("Search Customer Details");
        SearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerActionPerformed(evt);
            }
        });

        UpdateStock.setBackground(new java.awt.Color(153, 153, 255));
        UpdateStock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UpdateStock.setForeground(new java.awt.Color(0, 204, 0));
        UpdateStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/add.png"))); // NOI18N
        UpdateStock.setText("Add new stock");
        UpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStockActionPerformed(evt);
            }
        });

        Edit_delete.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Edit_delete.setText("Edit/Delete");
        Edit_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(Edit_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(UpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(Edit_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 170, 1330, 560);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/agroShopLogo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 253, 148);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Agro shop Management System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 800, 150);

        Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(153, 0, 0));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(1263, 20, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void SaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDetailsActionPerformed
        // TODO add your handling code here
        if(!CustomerName.getText().matches("[A-Za-z][a-zA-Z ]*")) { // validation for customerName text field
            JOptionPane.showMessageDialog(null, "UserName contians only Alphabet");
            return;
        }
        if(!CustomerMobile.getText().matches("[0-9]*")){
            JOptionPane.showMessageDialog(null, "mobile no contians only numbers");
            return;
        }
           
        if(CustomerName.getText().equals("") || CustomerMobile.getText().equals("")|| this.bt ){
            JOptionPane.showMessageDialog(null,"plz enter all details properly");
            return ;
        }
        
        try{
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select custid, mobile from Customer where mobile = ?"));
            Agro_Shop_Management.getPs().setString(1, CustomerMobile.getText());
            int custid = 0;
            try{
                ResultSet rs =  Agro_Shop_Management.getPs().executeQuery();
                if(rs.next()){
                    custid = rs.getInt(1);
                } else {
                    Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("insert into customer(cust_name, mobile) values(?,?)"));
                    Agro_Shop_Management.getPs().setString(1, CustomerName.getText());
                    Agro_Shop_Management.getPs().setString(2, CustomerMobile.getText());
                    System.out.println("Customer data: "+Agro_Shop_Management.getPs().executeUpdate());
                    
                    Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select custid from Customer where mobile = ?"));
                    Agro_Shop_Management.getPs().setString(1, CustomerMobile.getText());
                    rs =  Agro_Shop_Management.getPs().executeQuery();
                    if(rs.next())
                      custid = rs.getInt(1);
                    
                }
            } catch(SQLException | NumberFormatException e){
                   JOptionPane.showMessageDialog(null,e.getMessage());
                   System.out.println(e.getMessage());
                   return;
            }
            String c_date = ""+new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
            // Bill table update;
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("insert into bill(custid, bill_date, TotalAmount) values(?,?,?)"));
            Agro_Shop_Management.getPs().setInt(1, custid);
            Agro_Shop_Management.getPs().setString(2, c_date);
            Agro_Shop_Management.getPs().setString(3, ""+total);
            System.out.println("Bill details:"+ Agro_Shop_Management.getPs().executeUpdate());
            // get bill number
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select max(billno) from bill where custid = ?"));
            Agro_Shop_Management.getPs().setInt(1, custid);
            ResultSet rs = Agro_Shop_Management.getPs().executeQuery();
            int billno = 0;
            if(rs.next())
                billno = rs.getInt(1);
            System.out.println("Bill Created with billno: "+ billno+" record updated: ");
            
            // purchase table details update
            System.out.println("purchase array sixe: "+purchaseDetails.size());
            for(int i = 0; i < purchaseDetails.size(); i++) {
                Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("insert into purchaseDetails(billno, productid, quantity) values(?,?,?)"));
                Agro_Shop_Management.getPs().setInt(1, billno);
                Agro_Shop_Management.getPs().setInt(2, purchaseDetails.get(i).getProductId());
                Agro_Shop_Management.getPs().setInt(3, purchaseDetails.get(i).getQuantity());
                System.out.println((i+1)+" record  updated with : "+Agro_Shop_Management.getPs().executeUpdate());
                
                // decreament stock
                Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("update stock set quantity = ? where productId = ?"));
                Agro_Shop_Management.getPs().setInt(1, purchaseDetails.get(i).getStockQuantity() - purchaseDetails.get(i).getQuantity());
                Agro_Shop_Management.getPs().setInt(2, purchaseDetails.get(i).getProductId());
                System.out.println("Stock table :"+Agro_Shop_Management.getPs().executeUpdate());
                
            }
            PrintBill p = new PrintBill(CustomerName.getText(), CustomerMobile.getText(), billno, total);
            p.GenerateBill();
            p.setVisible(true);
            setValue();
            purchaseDetails = new ArrayList<>();
            Agro_Shop_Management.setPs(null);
        } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"exception problem in software plz contact developer"+e);
            //System.out.println("ex- "+e);
        }
        
    }//GEN-LAST:event_SaveDetailsActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        // TODO add your handling code here
        try{
            if(ProductName.getSelectedItem().toString().equals("") || Quantity.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"plz enter all details properly");
            return ;
            }
            int quantity =0;
            try{
                quantity = Integer.parseInt(Quantity.getText());
            } catch(Exception e){
               JOptionPane.showMessageDialog(null, "Enter Quantity in number only");
               return;
            }
            
            this.bt = false; // it will refer to Save details
            String p_name = ProductName.getSelectedItem().toString();
            //this.qun += Quantity.getText()+", ";
            ResultSet rs = Agro_Shop_Management.getSt().executeQuery("select productid, per_pack_rate, Quantity from stock where productName = '"+p_name+"'");
            
            if(rs.next() &&  quantity >= Integer.parseInt(rs.getString(3))){
               JOptionPane.showMessageDialog(null, "Selected Product is out of stock only "+rs.getString(3)+" product remains.");
               return;
            }
            this.total += quantity * Float.parseFloat(rs.getString(2));
            
            // add product to array of purchasedetails to use in save method;
            purchaseDetails.add(new PurchaseDetail(rs.getInt(1),quantity,rs.getInt(3)));
            
            TotalAmountText.setText(""+total);
            this.count ++;
            NoOfProduct.setText(""+this.count);
            Quantity.setText("");
            //System.out.println(p_name+" "+p_id+" "+b_no+" "+qun+" "+total+" "+rate);
        } catch(HeadlessException | SQLException | NumberFormatException e){
             System.out.println(e);
        JOptionPane.showMessageDialog(null,"Exception plz contact developer ");
        } 
        
    }//GEN-LAST:event_AddProductActionPerformed

    private void CustomerMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerMobileActionPerformed

    private void SearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            new SearchCustomerPage().setVisible(true);
        });
      
    }//GEN-LAST:event_SearchCustomerActionPerformed

    private void CustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDetailsActionPerformed
        // TODO add your handling code here:
          if(Agro_Shop_Management.getUserType().equals("owner")||Agro_Shop_Management.getUserType().toUpperCase().equals("OWNER")){
          java.awt.EventQueue.invokeLater(() -> {
              new SellDetailsPage().setVisible(true);
          });
    }//GEN-LAST:event_CustomerDetailsActionPerformed
         else {
              JOptionPane.showMessageDialog(null, "Only Owner Have right to view sell details");
          }
    }
    private void ViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStockActionPerformed
        // TODO add your handling code here:
                java.awt.EventQueue.invokeLater(() -> {
                    new ViewStock().setVisible(true);
                });

    }//GEN-LAST:event_ViewStockActionPerformed

    private void UpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStockActionPerformed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(() -> {
            new UpdatePage().setVisible(true);
        });
    }//GEN-LAST:event_UpdateStockActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        LoginPage l= new LoginPage();
        l.setVisible(true);
        try {
            Agro_Shop_Management.getCon().close();
        } catch (SQLException ex) {
            System.out.println("Exption in log out"+ex.getMessage());
        }
        this.dispose();
        
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void Edit_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_deleteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Coming in next version");
    }//GEN-LAST:event_Edit_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage.jpg")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JButton CustomerDetails;
    private javax.swing.JTextField CustomerMobile;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JButton Edit_delete;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NoOfProduct;
    private javax.swing.JComboBox<String> ProductName;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton SaveDetails;
    private javax.swing.JButton SearchCustomer;
    private javax.swing.JLabel TotalAmountText;
    private javax.swing.JButton UpdateStock;
    private javax.swing.JButton ViewStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
