/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;

import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PrintBill extends javax.swing.JFrame {

    /**
     * Creates new form PrintBill
     */
    private final  int billNo ;
    private final String customerName;
    private final String mobile;
    private final float totalAmount;
    private String c_date;
    public PrintBill(String name, String mobile, int billno, float total) {
        this.setResizable(false);
        this.billNo = billno;
        this.customerName = name;
        this.mobile = mobile;
        this.totalAmount = total;
        initComponents();
    }

    /**
     *
     * @param billNo
     * @param name
     * @param mobile
     */
    
     
    void GenerateBill(){
        BillArea.setText("*****************  Shree krushi Kendra ***************\n");
        BillArea.setText(BillArea.getText()+"           Burhanpur, Dist. Burhanpur(M.P)450331      \n\n");
        c_date = ""+new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        BillArea.setText(BillArea.getText()+"Bill No : "+billNo+"                                                                     Date: " +c_date+"\n");
        BillArea.setText( BillArea.getText()+"Customer Name : "+customerName+" \n"+"Mobile : "+mobile+"\n\n");
        BillArea.setText( BillArea.getText()+"====================================================================\n");
        
        try {
            //get purchase details of customer from database
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select s.productid, s.productName, s.batchno, p.quantity, s.per_pack_rate from stock as s inner join purchasedetails as p on p.productid = s.productid where p.billno = ?"));
            Agro_Shop_Management.getPs().setInt(1, this.billNo);
            int i = 1;
            ResultSet rs = Agro_Shop_Management.getPs().executeQuery();
            BillArea.append("S.No\t|");
            BillArea.append("ProductId\t|");
            BillArea.append("ProductName\t|");
            BillArea.append("BatchNo\t|");
            BillArea.append("Quantiy\t|");
            BillArea.append("Rate");
            BillArea.append("\n");
            
            while(rs.next()){
                BillArea.append(""+(i++)+"\t:");
                BillArea.append(rs.getString(1)+"\t:");
                BillArea.append(rs.getString(2)+"\t:");
                BillArea.append(rs.getString(3)+"\t:");
                BillArea.append(rs.getString(4)+"\t:");
                BillArea.append(rs.getString(5)+"");
                BillArea.append("\n");
                
            }
           rs = null;
           Agro_Shop_Management.setPs(null);
        
        } catch (SQLException ex) {
            Logger.getLogger(PrintBill.class.getName()).log(Level.SEVERE, null, ex);
        }
        BillArea.setText( BillArea.getText()+"\nTotalAmount   :  "+totalAmount+"\ttax included\n");
        BillArea.setText( BillArea.getText()+"\nSignature of shopOwner                           Signature Of customer\n");
      
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BillArea = new javax.swing.JTextArea();
        PrintBillFormate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BillArea.setColumns(22);
        BillArea.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        BillArea.setRows(5);
        jScrollPane1.setViewportView(BillArea);

        PrintBillFormate.setBackground(new java.awt.Color(153, 153, 255));
        PrintBillFormate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PrintBillFormate.setForeground(new java.awt.Color(204, 0, 0));
        PrintBillFormate.setText("PrintBill");
        PrintBillFormate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBillFormateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(PrintBillFormate)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrintBillFormate)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBillFormateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBillFormateActionPerformed
        // TODO add your handling code here:
        try {
            BillArea.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null,"Exception plz contact Developer \n"+ex);
        }
    }//GEN-LAST:event_PrintBillFormateActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillArea;
    private javax.swing.JButton PrintBillFormate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
