/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SearchCustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form SearchCustomerPage
     */
    public SearchCustomerPage() {
        this.setResizable(false);
        initComponents();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BillNoLabel = new javax.swing.JLabel();
        TakeBillNo = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showDetails = new javax.swing.JTable();
        BillNoLabel1 = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        BillNoLabel2 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        BillNoLabel3 = new javax.swing.JLabel();
        custMobile = new javax.swing.JTextField();
        BillNoLabel4 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2), "Search Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(204, 51, 0))); // NOI18N

        BillNoLabel.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BillNoLabel.setForeground(new java.awt.Color(0, 51, 51));
        BillNoLabel.setText("CustomerName");

        TakeBillNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TakeBillNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Search.setBackground(new java.awt.Color(153, 153, 255));
        Search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 102, 102));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        showDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "ProductName", "BatchNo", "quantity", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(showDetails);

        BillNoLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BillNoLabel1.setForeground(new java.awt.Color(0, 51, 51));
        BillNoLabel1.setText("Enter Bill no");

        custName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        custName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameActionPerformed(evt);
            }
        });

        BillNoLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BillNoLabel2.setForeground(new java.awt.Color(0, 51, 51));
        BillNoLabel2.setText("Date");

        Date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        BillNoLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BillNoLabel3.setForeground(new java.awt.Color(0, 51, 51));
        BillNoLabel3.setText("TotalAmount");

        custMobile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        custMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custMobileActionPerformed(evt);
            }
        });

        BillNoLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BillNoLabel4.setForeground(new java.awt.Color(0, 51, 51));
        BillNoLabel4.setText("Mobile");

        totalAmount.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TakeBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BillNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(BillNoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BillNoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BillNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(BillNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(558, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TakeBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BillNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillNoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillNoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BillNoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(BillNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try{
            if(!TakeBillNo.getText().matches("[0-9]*")|| "".equals(TakeBillNo.getText())){
                JOptionPane.showMessageDialog(null, "Plz enter vaild Bill no");
                return;
            }
            int b =(int)Integer.parseInt(TakeBillNo.getText());
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select c.cust_name, c.mobile, b.bill_date, b.totalAmount from bill as b inner join customer as c on b.custid = c.custid where b.billno=?"));
            Agro_Shop_Management.getPs().setInt(1, b);
            ResultSet rs = Agro_Shop_Management.getPs().executeQuery();
            if(rs.next()){
                custName.setText(rs.getString(1));
                custMobile.setText(rs.getString(2));
                Date.setText(rs.getString(3));
                totalAmount.setText(rs.getString(4));
            }else {
                    JOptionPane.showMessageDialog(null, "No record found");
                    return;
            }
            Agro_Shop_Management.setPs(Agro_Shop_Management.getCon().prepareStatement("select s.productid, s.productName, s.batchno, p.quantity, s.per_pack_rate from stock as s inner join purchasedetails as p on p.productid = s.productid where p.billno = ?"));
            DefaultTableModel model = (DefaultTableModel) showDetails.getModel();
            model.setRowCount(0);
            Agro_Shop_Management.getPs().setInt(1, b);
            rs = Agro_Shop_Management.getPs().executeQuery();
            boolean check=true;
            while(rs.next()){
                         Object o[]= {rs.getInt(1),rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)};
                         model.addRow(o);
                         check = false;
                        
            }
            if(check)
                JOptionPane.showMessageDialog(null, "No record found");
           
          
        } catch (NumberFormatException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null," problem plz contact developer   "+e);
        
        }
        
    }//GEN-LAST:event_SearchActionPerformed

    private void custNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void custMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custMobileActionPerformed

    private void totalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountActionPerformed

    /**
     * @param args the command line arguments
     */
  
    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage.jpg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BillNoLabel;
    private javax.swing.JLabel BillNoLabel1;
    private javax.swing.JLabel BillNoLabel2;
    private javax.swing.JLabel BillNoLabel3;
    private javax.swing.JLabel BillNoLabel4;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Search;
    private javax.swing.JTextField TakeBillNo;
    private javax.swing.JTextField custMobile;
    private javax.swing.JTextField custName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable showDetails;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables
}
